/// Marketplace
export const SET_MARKETPLACE = 'SET_MARKETPLACE'
export const SET_PRODUCTS ='SET_PRODUCTS'
export const CREAT_PRODUCT='CREATE_PRODUCT'
export const SHIP_PRODUCT= 'SHIP_PRODUCT'
export const RECEIVE_PRODUCT='RECEIVE_PRODUCT'
export const REGISTER_USER ='REGISTER_USER'

//UI
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_ERRORS ='SET_ERRORS'